### ISSUE TITLE
StoryFireUser.get_subscriber_count needs to use regex

### ISSUE THREAD

**Issue by meatyite** [sl4vkek/python-socialblade#7]
![image](https://user-images.githubusercontent.com/43294802/88050456-91670180-cb5f-11ea-947c-7bc71c1bb35e.png)
@SuperSonicHub1 i think StoryFire needs to use regex too

**Comment by SuperSonicHub1** [comment]
Oh yes, I've seen this error before. I believe it is the way that
Socialblade's API redirects users who make an invalid query. Let me do some
investigation and get back to you.

Kyle Williams

**Comment by SuperSonicHub1** [comment]
After doing a bit of investigation both within Python and the Network tab of Chrome, I have come to the conclusion that the issue with `StoryFireUser` is not with our code, but instead with either Cloudflare, and by extension `cloudscraper`, or is Socialblade's way of blocking external users. I say this because the same error occasionally takes place with `TwitchUser`, although on a much smaller scale. If it is the former, I would suggest you start an issue with [Cloudscraper](https://github.com/VeNoMouS/cloudscraper#updates). If it is the latter, we'll have to figure something out, or at least leave a warning that the function doesn't function 100% of the time

(P.S. I sent a message to you yesterday but it seemingly didn't get submitted. Sorry for the late response.)

**Comment by meatyite** [comment]
@SuperSonicHub1 Yes we should write a warning. We should also maybe modify `StoryFireUser.live_subscriber_count_generator`'s default request delay, since it will error more times?

**Comment by SuperSonicHub1** [comment]
Cool. I'll get on it.

Kyle Williams

**Comment by SuperSonicHub1** [comment]
#8. Check it out.

**Comment by meatyite** [comment]
Merged and updated to pypi. Next up: add examples for Dailymotion
